### ISSUE TITLE
更新后出现 AttributeError: 'Conv' object has no attribute 'ki'错误

### ISSUE THREAD

**Issue by xhoustgd70298** [mrathena/python.yolo.apex.autoaim.helper#5]
YOLOv5  2023-5-26 Python-3.9.16 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060, 12287MiB)

Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients
Traceback (most recent call last):
  File "D:\GameAiTools\python.yolo.apex.autoaim.helper-master\detect.realtime.py", line 11, in <module>
    detector = Detector(weight)
  File "C:\Users\ZD\anaconda3\envs\tmp_env_yolo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\GameAiTools\python.yolo.apex.autoaim.helper-master\toolkit.py", line 262, in __init__
    self.model.warmup(imgsz=(1 if self.pt else bs, 3, *self.imgsz))  # warmup
  File "D:\GameAiTools\python.yolo.apex.autoaim.helper-master\models\common.py", line 533, in warmup
    return forward_call(*args, **kwargs)
  File "D:\GameAiTools\python.yolo.apex.autoaim.helper-master\models\yolo.py", line 192, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "D:\GameAiTools\python.yolo.apex.autoaim.helper-master\models\yolo.py", line 106, in _forward_once
    y.append(x if m.ki in self.save else None)  # save output
  File "C:\Users\ZD\anaconda3\envs\tmp_env_yolo\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv' object has no attribute 'ki'

**Comment by xhoustgd70298** [comment]
自己解决了 猜测是 yolo版本问题 把原版的yolo换成 5.7.2就行了 直接从仓库里下载会有这个问题
